name = "HydroModelCore"
uuid = "57609f06-44cb-4626-8f6d-47ea844d0af1"
version = "0.3.0"
authors = ["jingx <50790703+chooron@users.noreply.github.com>"]

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
ComponentArrays = "0.15"
DocStringExtensions = "0.9"
Printf = "1.11"
RuntimeGeneratedFunctions = "0.5"
SymbolicUtils = "4"
Symbolics = "6, 7"
julia = "1"
